openapi: "3.0.1"
info:
  title: "shipconnect-stg"
  description: "ShipConnect - API Gateway - stg"
  version: "2024-11-04T16:50:28Z"
servers:
- url: "https://stg-shipconnect-api.umamigroup.vn"
paths:
  /delivery/shipping/hook:
    post: {}
  /delivery/ecommerce/order-status:
    post:
      security:
      - api_key: []
  /onboard/connect:
    post:
      security:
      - api_key: []
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /delivery/ecommerce/hook:
    post:
      security:
      - api_key: []
  /onboard/token:
    post:
      security:
      - api_key: []
  /onboard/setting:
    get:
      security:
      - api_key: []
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
x-amazon-apigateway-policy:
  Version: "2012-10-17"
  Statement:
  - Effect: "Allow"
    Principal: "*"
    Action: "execute-api:Invoke"
    Resource: "arn:aws:execute-api:us-east-2:619071331064:tuh4u5b6md/*"
  - Effect: "Deny"
    Principal: "*"
    Action: "execute-api:Invoke"
    Resource: "arn:aws:execute-api:us-east-2:619071331064:tuh4u5b6md/*"
    Condition:
      NotIpAddress:
        aws:SourceIp:
        - "103.69.193.181/32"
        - "203.171.22.6/32"
        - "125.235.4.59/32"
        - "115.78.1.178/32"
        - "171.243.49.3/32"
