openapi: "3.0.1"
info:
  title: "shipconnect-stg"
  description: "ShipConnect - API Gateway - stg"
  version: "2024-11-04T16:50:28Z"
servers:
- url: "https://stg-shipconnect-api.umamigroup.vn"
paths:
  /delivery/shipping/hook:
    post: {}
  /delivery/ecommerce/order-status:
    post:
      security:
      - api_key: []
  /onboard/connect:
    post:
      security:
      - api_key: []
  /delivery/ecommerce/hook:
    post:
      security:
      - api_key: []
  /onboard/token:
    post:
      security:
      - api_key: []
  /onboard/setting:
    get:
      security:
      - api_key: []
components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
